# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baefa9e2f8e8a7619f8944c9656458b0e1adbe80fa4e6f3d0f68e50b56199ecedc25f0fef64ae1f6a3358bfb9c0f8f82c55c4a6c6ddb2c7a98c16aa4babe7de0

test:
  secret_key_base: 479151e51305216b432a8b02832f9b4eccaf9bb0a074e743b3a47ad44ceb36745f94dcc957e9248280ae94aacc6b6a0aea2d211252e6f1ae84c1c77b74f028bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
